#---------------------------
# Hexo Theme Fluid
# Github: https://github.com/fluid-dev/hexo-theme-fluid
#
# 配置指南: https://hexo.fluid-dev.com/docs/guide/
# 你可以从指南中获得更详细的说明

# demo链接：https://zkqiang.cn/about/
# github 地址：https://github.com/GHTYQ/GHTYQ.github.io/blob/master/_config.fluid.yml

#---------------------------


#---------------------------
# 全局
# Global
#---------------------------